# Generated by Django 6.0 on 2025-12-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biyokaab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='distance_cm',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='water_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
