# Generated by Django 6.0 on 2025-12-15 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('xagaa', 'Xagaa'), ('gu', "Gu'"), ('dayr', 'Dayr')], max_length=12)),
                ('days_until_rainfall', models.PositiveIntegerField()),
                ('source', models.CharField(default='FAO_SWALIM', max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_snapshots', to='water.location')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('water_level', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soil_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('motion_detected', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='water.sensor')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('farmer', 'Farmer'), ('nomad', 'Nomad')], max_length=12)),
                ('fog_system_type', models.CharField(blank=True, max_length=50)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterDemandUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('human', 'Human'), ('livestock', 'Livestock'), ('crop', 'Crop')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('count', models.PositiveIntegerField(default=1)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('daily_need_liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_units', to='water.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WaterSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('system_type', models.CharField(choices=[('portable_fog_net', 'Portable Fog Net'), ('fixed_fog_net', 'Fixed Fog Net')], max_length=32)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_systems', to='water.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WaterStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tank', max_length=120)),
                ('capacity_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_volume_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='water.watersystem')),
            ],
        ),
        migrations.CreateModel(
            name='WaterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_text', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('priority_rules', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_plans', to='water.userprofile')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_plans', to='water.watersystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='water.watersystem'),
        ),
    ]
