# Generated by Django 5.0.8 on 2025-12-16 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='distance_cm',
            field=models.FloatField(blank=True, help_text='Distance from sensor to water surface in cm', null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='system',
            field=models.ForeignKey(blank=True, help_text='Optional: can be auto-created from MQTT without system', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='water.watersystem'),
        ),
    ]
